### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by rittkeviq** [mattcanty/lichess-cli#7]
Hey,

I got the problem that I'm not able to install the client. When I use the make install command I receive the following error:

`go test`
`make: go: Kommando nicht gefunden`
`make: *** [Makefile:2: test] Fehler 127`

Can you help me with that?

**Comment by mattcanty** [comment]
Assuming the following but please confirm:
1. You're on a Mac
2. Make normally works
3. You have Golang installed

I just tested against `master`, please observe the following output:

```
➜  lichess-cli git:(master) go version
go version go1.16.3 darwin/amd64
➜  lichess-cli git:(master) make
go test

PASS
ok      github.com/mattcanty/lichess-cli        0.375s
```

**Comment by rittkeviq** [comment]
Thank you for your help. Now I was able to install it. I didn't know that I have to install Golang. I'm not on a Mac but on a RaspberryPi.

**Comment by mattcanty** [comment]
I see. The real issue here is I haven’t yet prepared a release so that you
can just use it!

I’ll make time for that soon.

**Comment by mattcanty** [comment]
Hey! I know it's been a while. I've added releases and you want this one for Raspberry Pi - [lichess-cli_1.0.2_Linux_armv5.tar.gz](https://github.com/mattcanty/lichess-cli/releases/download/v1.0.2/lichess-cli_1.0.2_Linux_armv5.tar.gz)
